### ISSUE TITLE
编译报 QuickStartJavaApp.java:48: cannot find symbol 。。。location: class com.streamxhub.streamx.common.util.JsonUtils

### ISSUE THREAD

**Issue by lmhongwei** [streamxhub/streampark-quickstart#14]
[ERROR] [Error] /home/hudi/streamx-console-service-1.2.2/streamx_workspace/project/streamx-quickstart/streamx-quickstart-main/quickstart-datastream/datastream_1.12/src/main/java/com/streamxhub/streamx/flink/quickstart/datastream/QuickStartJavaApp.java:48: cannot find symbol
symbol: method read(java.lang.String,java.lang.Class<com.streamxhub.streamx.flink.quickstart.datastream.JavaUser>)
location: class com.streamxhub.streamx.common.util.JsonUtils
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for StreamX Quickstart 1.2.2:
[INFO]
[INFO] StreamX Quickstart ................................. SUCCESS [ 2.773 s]
[INFO] Quickstart Flink Job ............................... SUCCESS [ 12.451 s]
[INFO] Quickstart StreamX DataStream Job .................. SUCCESS [ 0.062 s]
[INFO] Quickstart StreamX DataStream Job For Flink 1.12 ... FAILURE [ 11.347 s]
[INFO] Quickstart StreamX DataStream Job For Flink 1.13 ... SKIPPED
[INFO] Quickstart StreamX DataStream Job For Flink 1.14 ... SKIPPED
[INFO] Quickstart StreamX FlinkSQL Job .................... SKIPPED
[INFO] Quickstart StreamX FlinkSQL Job For Flink 1.12 ..... SKIPPED
[INFO] Quickstart StreamX FlinkSQL Job For Flink 1.13 ..... SKIPPED
[INFO] Quickstart StreamX FlinkSQL Job For Flink 1.14 ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.099 s
[INFO] Finished at: 2022-04-04T10:10:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile (default-cli) on project datastream_1.12: Execution default-cli of goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile failed.: CompileFailed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by silenceStar** [comment]
> fixed.

i have the same question,how to deal with it?
